// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATHHJzl0i0bYXMltl1NqSb29unjDixD3M',
    appId: '1:985679342823:web:79d2b4c7f6c62ce6c1c642',
    messagingSenderId: '985679342823',
    projectId: 'eypop-c3e1d',
    authDomain: 'eypop-c3e1d.firebaseapp.com',
    storageBucket: 'eypop-c3e1d.appspot.com',
    measurementId: 'G-Z4RFJGCY0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCavZ73K47pQbLLY9DrQsbuQHixEsL76oY',
    appId: '1:985679342823:android:1c71d08f9e7a7ca1c1c642',
    messagingSenderId: '985679342823',
    projectId: 'eypop-c3e1d',
    storageBucket: 'eypop-c3e1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsGD8ACe5z2iigq3PN3gH4sP5iGtnw-v4',
    appId: '1:985679342823:ios:39cfc18c3b604939c1c642',
    messagingSenderId: '985679342823',
    projectId: 'eypop-c3e1d',
    storageBucket: 'eypop-c3e1d.appspot.com',
    androidClientId: '985679342823-1moanrktragq82jboc21t22l5vtbhcp3.apps.googleusercontent.com',
    iosClientId: '985679342823-8h1s8cg2ockm58dvtaq61roh34emuf8n.apps.googleusercontent.com',
    iosBundleId: 'com.actuajeriko.eypop',
  );
}
